#!/usr/bin/env bash
# script to display "To infinity and beyond" infinitely with sleep 2. Print "I am invincible!!!" when recieved SIGTERM signal
pgrep -f 100-process_and_pid_file > /var/run/holbertonscript.pid
trap 'echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit' 15 3
trap 'echo "Y U no love me?!"' 2
while true;
do
    echo "To infinity and beyond"
    sleep 2
done
