#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd only displaying username, user id, home directory path for user
while read line; do
      echo "$line" | cut -d':' -f 1,3,6
done < /etc/passwd