#!/usr/bin/env bash
# script that displays content of the file "/etc/passwd" in the format - "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
while IFS=":" read uname pass uid gid uidinfo home shell; do
      echo "The user $uname is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $uidinfo"
done < /etc/passwd
