#!/usr/bin/env bash
# Script that loops from 1-10 and displays "bad luck" for 4th iteration, "good luck" for 8th iteration and "Holberton School" for other iterations
i=1
while [ $i -le 10 ]; do
      if [ $i -eq 4 ]; then
      	 echo "bad luck"
      elif [ $i -eq 8 ]; then
      	   echo "good luck"
      else
	echo "Holberton School"
      fi
      let i=i+1
done
