#!/usr/bin/env bash
# Script that gives information about the "holbertonschool" file
fl=holbertonschool
if [ -e $fl ]; then
   echo "holbertonschool file exists"
   if [ -s $fl ]; then
      echo "holbertonschool file is not empty"
   else
      echo "holbertonschool file is empty"
   fi
   if [ -f $fl ]; then
      echo "holbertonschool is a regular file"
   fi
else
	echo "holbertonschool file does not exist"
fi
